#!/bin/bash -l

#$ -cwd
#$ -S /bin/bash
#$ -l tmem=16G
#$ -t 1-1
#$ -l h_rt=01:00:00
#$ -o /SAN/intelsys/rclearn/when-do-reading-comprehension-models-learn/array.out
#$ -e /SAN/intelsys/rclearn/when-do-reading-comprehension-models-learn/array.err


hostname
date

# Activate conda environment
conda activate rclearn

export LANG="en_US.utf8"
export LANGUAGE="en_US:en"

cd /SAN/intelsys/rclearn/when-do-reading-comprehension-models-learn


test $SGE_TASK_ID -eq 1 && sleep 10 && bash jobs/checklist/processing.job

date
